version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - arpk
  - cachix
  - fetchurl
  - fetchzip
  - gltf
  - kwaa
  - libgcc
  - moeru
  - nixpkgs
  - passthru
  - patchelf
  - pname
  - stdenv
ignoreWords: []
import: []
